### PR TITLE
Added support for passing AppboyOptions to SegAppboyIntegration

### PR DESCRIPTION
**Pull request by maloneranger**
The purpose of this PR is to add support for Braze to collect the IDFA whenever the AppBoy SDK is being instantiated by the Segment-Appboy integration.

See [Braze Documentation](https://www.braze.com/docs/developer_guide/platform_integration_guides/ios/initial_sdk_setup/optional_idfa_collection/#optional-idfa-collection) for information on collecting the IDFA.

Personal use case for requiring this was for allowing targeted marketing in Braze based on installs from different marketing campaigns in AppsFlyer.

### Update

I made some changes to this fork to make it a bit more generic. Rather than accepting only the IDFADelegate, it will take a dictionary of configuration options that can then be mapped into the appboyOptions.

I used a custom enum to expose the available Braze configuration keys to the user of the SDK. This way they can have everything required to use the integration exposed by it, without the user having to reach into the AppBoySDK. It also allowed for me to prevent usage of the `ABKSDKFlavorKey` and `ABKEndpointKey`, as the integration explicitly sets those itself.

### CODE REVIEW

**Comment by maloneranger** [comment]
@Bucimis @chshapiro Is this something you might be interested in including in the SDK?

**Comment by maloneranger** [comment]
Hey @Bucimis @chshapiro 

Wondering if you could leave a comment letting me know if this is something you'd like to include in the SDK? For myself it would obviously be good to be able to keep up to date with the SDK, but if your not interested in the changes I can continue using my fork.

**Comment by Bucimis** [comment]
@maloneranger we're definitely looking at incorporating either this PR or a generalized variant that allows folks to pass their `appboyOption` into the init function. Our timeline is likely ~4-6 weeks so in the meantime I'd continue to use the fork. Many thanks for the contribution :)

**Comment by maloneranger** [comment]
@Bucimis Cool, thanks for the update! I actually pushed some changes today to make it a bit more generalised to allow the options to be passed instead of just the IDFADelegate. I wrote a small update in the description, but actually will update title of the PR to match as well.

**Comment by chshapiro** [comment]
Hey @maloneranger,

Thanks for this contribution! We've incorporated the concept into our latest release 3.1.0.

**Pull request closed without merging**
